### ISSUE TITLE
Change status bar icon when paused

### ISSUE THREAD

**Issue by davidlago** [ComputeForHumanity/compute-for-humanity-app#18]
As I was trying to preserve my battery while in a conference, I paused it. Later on, I didn't quite remember having done this, and was wondering if it was paused or not. It would be nice if the status bar icon showed some kind of pause symbol overlaid to the app logo or something. Just a tiny feature request, but not essential at all. Thanks for the amazing job!

**Comment by JacobEvelyn** [comment]
Great request; makes a ton of sense. OS X is getting increasingly strict about what sort of things you can do with icons (just look at how Safari handles favicons) but I'll see if this is possible. I agree it would be nice.

On a side note, have you noticed this impacting your machine's battery life? If so that's definitely something I want to look into as well.

**Comment by davidlago** [comment]
No, I haven't noticed any decrease in battery life... just trying to save as much as possible during the conference and thought this was an app I could go without for a bit.

**Comment by JacobEvelyn** [comment]
Awesome, thanks for the info! I'll let you know when this is implemented.

**Comment by JacobEvelyn** [comment]
@davidlago I just made the change; the new version will go out to the website in the next few days for download. Because it uses Apple's standard graying and the existing logo is very thin, the effect is fairly subtle. I'll be the first to admit it could be improved.

But let's keep an eye on it and see if it's usable enough after a few days of use or if it's too hard to differentiate the grayed version from the standard version.

**Comment by JacobEvelyn** [comment]
I just deployed the new version to the website. Let me know what you think!
