### ISSUE TITLE
Failed to look for updates after upgrading to El Capitan

### ISSUE THREAD

**Issue by davidlago** [ComputeForHumanity/compute-for-humanity-app#20]
Don't know if related to my recent upgrade to OS X "El Capitan", but I'm getting this error when looking for updates:

![screen shot 2015-10-14 at 11 02 57 am](https://cloud.githubusercontent.com/assets/5722719/10487740/7cbe15c0-7263-11e5-9672-c1eb314a3f0d.png)

**Comment by JacobEvelyn** [comment]
Thanks for the bug report! I'll look into this in the next few days. Likely a small configuration change is all that's required.

**Comment by JacobEvelyn** [comment]
Hmm. It appears the issue is that I don't use HTTPS for downloads: https://github.com/sparkle-project/Sparkle/issues/644 I'll have to think about workarounds, since I would prefer not to pay for SSL if possible.

**Comment by JacobEvelyn** [comment]
Found a workaround! Unfortunately, you won't be able to update via the app and will need to install the latest version (1.12) manually via the website.

The issue is that El Capitan made a change to only allow non-HTTPS requests that are whitelisted within the app. Since your version doesn't contain the whitelist, there's no way for you successfully make the version request. Sorry for the hassle—wish I had caught this sooner!

**Comment by davidlago** [comment]
Thanks for looking into this, version 1.12 installed!
